# Generated by Django 3.1.2 on 2020-10-25 15:43

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumBlog',
            fields=[
                ('Blog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Author', models.CharField(max_length=150)),
                ('Title', models.CharField(max_length=150)),
                ('Blog_Cover', models.ImageField(blank=True, upload_to='premium_images/')),
                ('Date_Posted', models.DateField(default=django.utils.timezone.now)),
                ('Description', models.TextField()),
            ],
        ),
    ]
