# Generated by Django 3.1.2 on 2020-10-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_premium', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premiumblog',
            options={'permissions': [('special_status', 'Can read all blogs')]},
        ),
    ]
