# Generated by Django 3.1.2 on 2020-10-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_role',
            field=models.CharField(choices=[('employee', 'Employee'), ('student', 'Student'), ('job seeker', 'Job Seeker')], default=None, max_length=12),
        ),
    ]
