# Generated by Django 3.1.2 on 2020-10-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201016_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_is_varified',
            field=models.BooleanField(default=False),
        ),
    ]
