# Generated by Django 3.1.2 on 2020-10-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_email_is_varified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_is_varified',
        ),
    ]
