# Generated by Django 3.1.2 on 2020-10-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201018_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='account_role',
        ),
    ]
