# Generated by Django 3.1.2 on 2020-10-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_is_posted_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
