# Generated by Django 3.1.2 on 2020-10-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image_url',
            new_name='image_thumbnail',
        ),
    ]
