# Generated by Django 3.1.2 on 2020-10-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostJobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=150)),
                ('Company', models.CharField(max_length=150)),
                ('Job_location', models.CharField(max_length=250)),
                ('Employee_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('self-employed', 'Self-employed'), ('internship', 'Internship'), ('seasonal', 'Seasonal')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostJobPartTwoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Add_skills', models.TextField()),
                ('Email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
