# Generated by Django 3.1.2 on 2020-10-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
