# Generated by Django 3.1.2 on 2020-10-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjobmodel',
            name='Is_active',
        ),
    ]
