# Generated by Django 3.1.2 on 2020-10-24 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_remove_postjobmodel_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobmodel',
            name='Job_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
