# Generated by Django 3.1.2 on 2020-10-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_postjobmodel_job_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjobmodel',
            name='Email_address',
        ),
    ]
