# Generated by Django 3.1.2 on 2020-10-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20201025_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='Applicant_id',
            new_name='Applicant',
        ),
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='Job_id',
            new_name='Job',
        ),
    ]
