# Generated by Django 3.1.2 on 2020-10-19 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileEducation',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('School_or_College_or_University', models.CharField(max_length=250)),
                ('Degree', models.CharField(max_length=250)),
                ('Field_of_study', models.CharField(max_length=250)),
                ('Start_year', models.DateField()),
                ('Endt_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileExperience',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=250)),
                ('Employee_type', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('self-employed', 'Self-employed'), ('internship', 'Internship'), ('seasonal', 'Seasonal')], max_length=20)),
                ('Company', models.CharField(max_length=250)),
                ('Start_year', models.DateField()),
                ('Endt_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileMainInfo',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_image', models.ImageField(upload_to='profile_pic/')),
                ('headline', models.CharField(max_length=50)),
                ('current_position', models.CharField(blank=True, max_length=100)),
                ('aboutYourself', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileSkill',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Skill', models.CharField(max_length=250)),
            ],
        ),
    ]
