# Generated by Django 3.1.2 on 2020-10-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20201022_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='User_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
    ]
