# Generated by Django 3.1.2 on 2020-10-19 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_auto_20201019_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('u_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_image', models.ImageField(upload_to='profile_pic/')),
                ('headline', models.CharField(max_length=50)),
                ('current_position', models.CharField(blank=True, max_length=100)),
                ('aboutYourself', models.CharField(blank=True, max_length=400)),
                ('School_or_College_or_University', models.CharField(max_length=250)),
                ('Degree', models.CharField(max_length=250)),
                ('Field_of_study', models.CharField(max_length=250)),
                ('Education_Start_year', models.DateField()),
                ('Education_End_year', models.DateField()),
                ('Title', models.CharField(max_length=250)),
                ('Employee_type', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('self-employed', 'Self-employed'), ('internship', 'Internship'), ('seasonal', 'Seasonal')], max_length=20)),
                ('Company', models.CharField(max_length=250)),
                ('Start_year', models.DateField()),
                ('Endt_year', models.DateField()),
                ('Skill', models.CharField(max_length=250)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofileexperience',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprofilemaininfo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userprofileskill',
            name='id',
        ),
        migrations.DeleteModel(
            name='UserProfileEducation',
        ),
        migrations.DeleteModel(
            name='UserProfileExperience',
        ),
        migrations.DeleteModel(
            name='UserProfileMainInfo',
        ),
        migrations.DeleteModel(
            name='UserProfileSkill',
        ),
    ]
