# Generated by Django 3.1.2 on 2020-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20201019_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Endt_year',
            new_name='End_year',
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='aboutYourself',
            field=models.TextField(blank=True),
        ),
    ]
