# Generated by Django 3.1.2 on 2020-11-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20201101_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='User_image',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
