# Generated by Django 3.1.2 on 2020-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20201019_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Skill',
            field=models.TextField(),
        ),
    ]
