# Generated by Django 3.1.2 on 2020-10-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20201019_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Title',
            new_name='Experience_Title',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='aboutYourself',
            new_name='Summary',
        ),
    ]
