# Generated by Django 3.1.2 on 2020-11-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20201102_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='User_image',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
