# Generated by Django 3.1.2 on 2020-10-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20201019_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Company',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='End_year',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Experience_Title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='Start_year',
            field=models.DateField(blank=True),
        ),
    ]
