# Generated by Django 3.1.2 on 2020-10-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20201019_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='current_position',
            new_name='Current_position',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='headline',
            new_name='Headline',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='user_image',
            new_name='User_image',
        ),
    ]
